import glob
import os
import snakemake

#snakemake.shell.prefix("set -eo pipefail;")

import glob, sys

input_files = glob.glob('data_input/*')

output_files = []
for file in input_files:
	output = file.replace('_input.txt', '_output.txt')
	output_files.append(f'{output}') 

localrules: all

rule all:
	input:
		'combo.txt'

rule test:
	input:
		'data_input/{filename}_input.txt'
	output:
		'data_input/{filename}_output.txt'
	conda:
		"courtney_py38.yml"
	shell:
		"""
			python test.py -file {input}
		"""

rule combo:
	input:
		output_files
	output:
		'combo.txt'
	conda:
		"courtney_py38.yml"
	shell:
		"""
			python combo.py
		"""