import glob
import os
import snakemake

#snakemake.shell.prefix("set -eo pipefail;")

import glob, sys

input_files = glob.glob('data_input/*')

output_files = []
for file in input_files:
	output = file.replace('input', 'output')
	output_files.append(f'{output}') 

#localrules: all
rule clean:
	shell:
		"rm -f {output_files} combo.txt"

rule all:
	input:
		'combo.txt'

rule test:
	input:
		'data_input/{filename}_input.txt'
	output:
		'data_output/{filename}_output.txt'
	conda:
		"courtney_py38.yml"
	shell:
		"""
			python3 test.py -file {input}
		"""

rule combo:
	input:
		output_files
	output:
		'combo.txt'
	conda:
		"courtney_py38.yml"
	shell:
		"""
			python3 combine.py
		"""
