import glob
import os
import snakemake

#snakemake.shell.prefix("set -eo pipefail;")

# rule all:
# 	"{dataset}_output.txt"

localrules: test

rule test:
	input:
		"courtney_input.txt"
	output:
		"courtney_output.txt"
	conda:
		"courtney_py38.yml"
	shell:
		"""
			python test.py -dataset courtney
		"""
